<?php 

include "ExcepcionPropiaClase.php" ;

try {
    ExcepcionPropiaClase::testNumber(4);
    echo "El nÃºmero introducido es distinto de 0 ";
    ExcepcionPropiaClase::testNumber(0); 
    echo "Esto no se imprimirÃ¡";
} catch (ExcepcionPropia $e) {
    echo "Se ha producido una excepciÃ³n personalizada: " . $e->getMessage() . "";
} catch (Exception $e) {
    echo "Se ha producido una excepciÃ³n: " . $e->getMessage() . "";
}